apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-onboarding-pyme
  namespace: pyme
  annotations:
    kubernetes.io/change-cause: "{{ bamboo_deploy_version }} {{ gitcommit }} {{ environment }}"
  labels:
    app: fe-onboarding-pyme
    environment: {{ environment }}
spec:
  replicas: {{ replicas }}
  selector:
    matchLabels:
      app: fe-onboarding-pyme
      environment: {{ environment }}
  template:
    metadata:
      labels:
        app: fe-onboarding-pyme
        environment: {{ environment }}
    spec:
      containers:
        - name: fe-onboarding-pyme
          image: gcr.io/core-prod-307119/sisalefor/fe-onboarding-pyme:{{ gitcommit }}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /fe-onboarding-pyme/
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /fe-onboarding-pyme/
              port: 80
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
      dnsPolicy: Default
      imagePullSecrets:
        - name: gcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: fe-onboarding-pyme
  namespace: pyme
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: fe-onboarding-pyme
    environment: {{ environment }}
spec:
  selector:
    app: fe-onboarding-pyme
    environment: {{ environment }}
  type: ClusterIP
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fe-onboarding-pyme
  namespace: pyme
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fe-onboarding-pyme
  minReplicas: {{ replicas }}
  maxReplicas: {{ max_replicas }}
  targetCPUUtilizationPercentage: 50
