apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: dr-{{ application }}
  namespace: {{ namespace }}
spec:
  host: {{ application }}.{{ namespace }}.svc.cluster.local
  subsets:
    - name: {{ application }}
      labels:
        app: {{ application }}